# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CalendarTestOne' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CalendarTestOne

  pod 'FSCalendar'
  pod 'RealmSwift'

  target 'CalendarTestOneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CalendarTestOneUITests' do
    # Pods for testing
  end

end
